version: '3'

services:

  nginx:
    image: nginx:latest
    build: ./frontend
    environment:
      ENV NODE_ENV: production
      ENV BACKEND_URL: http://localhost:8080
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  payload:
    image: node:18-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 8080
      NODE_ENV: development
      PAYLOAD_SECRET: d1740aedbcb7c864a10816c6

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:



